### ISSUE TITLE
[Feature Request] Wyze Vacuum

### ISSUE THREAD

**Issue by tensiondriven** [SecKatie/ha-wyzeapi#281]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to trigger operation of my Wyze Robot Vacuum, check status, and get statistics about usage.
 
**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/shauntarves/wyze-sdk/blob/master/wyze_sdk/models/devices/vacuums.py

**Comment by yoinx** [comment]
Unfortunately, neither myself nor Josh (as far as I know) own a wyze vacuum to collect info from or to test against... So I wouldn't hold my breath on this unless someone that does own one collects the data/tests/submits a PR.

**Comment by kghantous** [comment]
I recently purchased a Wyze Vacuum, and I'd be happy to do the work on this if someone could give me a little guidance. I'm fairly new to HACS, but I've done c# web development and network management for 20 years, so a quick point in the right should be all I need.

**Comment by tensiondriven** [comment]
All I can suggest is taking a look at an existing vacuum, such as Shark:

https://github.com/home-assistant/core/tree/dev/homeassistant/components/sharkiq

There are probably guides for building HA components, alas, I've never made one and don't know any of the details.  Maybe @yoinx  or @JoshuaMulliken can provide some pointers.

**Comment by JoshuaMulliken** [comment]
@kghantous start by looking over the wyzeapy code [here](https://github.com/joshuamulliken/wyzeapy) that will help you to understand where the code needs to be added so the api's can be called. 

@yoinx and I have been using MITM techniques like Burp Suite and mitmproxy to understand the api endpoints that the software relies on so that is a great place to start as well. 

@tensiondriven is right on with the idea to look at other integrations. I looked very heavily at other integrations while doing the initial development

**Comment by sisimomo** [comment]
I personally have no problem providing a wyze account with access to my vacuum so you can add this feature. Moreover, I am ready to offer you my time if it is necessary to do some tests.

I saw that a [custom integration](https://github.com/romedtino/simple-wyze-vac) was made especially for Wyze vacuums. But, I find it sad to have a second integration just for my vacuum cleaner. I also have a 2FA account but this integration [does not support it](https://github.com/romedtino/simple-wyze-vac#prerequisites).

The [library](https://github.com/shauntarves/wyze-sdk) used by the [integration mentioned above](https://github.com/romedtino/simple-wyze-vac) could probably help you add Wyze vacuums. Also, I saw [the previous issue](https://github.com/JoshuaMulliken/ha-wyzeapi/issues/107) regarding this same request.

**Comment by sisimomo** [comment]
Hi @yoinx and @JoshuaMulliken,

Would any of you like to contact me so that we can determine the elements necessary to add this feature. As indicated above, I am able to provide everything you would like to implement the functionality. I own a [Wyze Robot Vacuum](https://wyze.com/wyze-robot-vacuum.html) so I am able to do the necessary testing to implement this feature.

Thanks!

**Comment by JoshuaMulliken** [comment]
@sisimomo I do not have the time to implement this feature but let's loop in @brg468 and @yoinx to see if any of them have the bandwidth.

I am happy to help w/ code review and merging changes

**Comment by sisimomo** [comment]
Its good!

I did as said and here is the result.

[History_export.csv](https://github.com/JoshuaMulliken/ha-wyzeapi/files/8052285/History_export.csv)

[OWASP_Zap_session.zip](https://github.com/JoshuaMulliken/ha-wyzeapi/files/8052286/OWASP_Zap_session.zip)

[Here is a video](https://youtu.be/Ssc6ZIDmz4E) showing the actions performed in the application to get this dump.

Feel free to make other requests if necessary.

Also, when you have a beta version, I can quickly test it without any problem.

Thanks!

**Comment by yoinx** [comment]
So I'm trying to read through these logs and correlate them to the video. It looks like all that the vacuum would need in HA is basically just a vacuum with status, battery, and vacuum state?  Unfortunately, it looks like you're selecting a room for it to travel to in order to start vacuuming. I'm not sure how to decode those from the map data just yet though. I may have to go look at some other integrations now that I have the json data to compare to so I can try and decipher what they're doing as well.

Here's the [vacuum entity](https://developers.home-assistant.io/docs/core/entity/vacuum/) that I'm comparing to. I'm not sure how (or if it's even possible without a custom card) to implement a map in HA.

**Comment by sisimomo** [comment]
Hi,

It would certainly be interesting to have the vacuum cleaner map in Home Assistant but it seems relatively complicated. I found someone who did [something similar](https://github.com/PiotrMachowski/Lovelace-Xiaomi-Vacuum-Map-card) with robot vacuums from Xiaomi (Roborock/Viomi/Dreame/Roidmi).

But in my opinion, the implementation of the [vacuum entity](https://developers.home-assistant.io/docs/core/entity/vacuum/) would already be a big step forward and what most people will use. But you are of course free to decide what you want to do. I will help you no matter what.

For the [vacuum entity](https://developers.home-assistant.io/docs/core/entity/vacuum/), this is what it currently looks like. (I currently use [this custom HACS integration](https://github.com/romedtino/simple-wyze-vac)).

![image](https://user-images.githubusercontent.com/27745204/153780611-7133b215-0001-45c0-84cf-ff73d4c80d54.png)
PS: I know it's not a Roomba. But I'm used to my robot vacuums "Roomba" even if those aren't from iRobot...

You will notice that it is possible to set the speed of the fan. In the video I forgot to show this feature. If you want, I'll give you one.

**Comment by yoinx** [comment]
It wouldn't hurt. But I'm not sure how long it's going to take me to implement any of this. That simple vac integration is heavily reliant on wyze-sdk. So I'm going to see how he's doing things I guess. The commands themselves don't seem super complicated, but they do rely on room names and everything, so I will have to at least figure out how he's decoding those. 

That simple vac integration looks like it's really depending on users to provide data to it through scripts and such as well. I'm not sure how clean that would end up being in practice. But like you said, it would at least get some functionality.

**Comment by tensiondriven** [comment]
Just dropping in to say I'm really impressed with everyone's contribution to this thread so far - Especially how thorough those logs are!  Impressive.

**Comment by yoinx** [comment]
Don't want to leave this hanging. Given my recent exponentially growing disdain for these devices, I won't be working on adding anything.

Sorry.

**Comment by sisimomo** [comment]
Pas de problème! Merci pour votre honnêteté.

@yoinx, @JoshuaMulliken and @brg468, est-ce que quelqu'un d'autre serait en mesure de résoudre ce problème?

Autrement, je vais continué a utilisé [simple-wyze-vac](https://github.com/romedtino/simple-wyze-vac). A date, je n'ai eu aucun problème. La seule chose un peu héritante, c'est que je doit rouler script pour mettre a jours le status de l'aspirateur. J'utilise personellement un version que j'ai un peu modifié du [blueprint](https://community.home-assistant.io/t/a/358828) de [Noblewolf](https://community.home-assistant.io/u/Noblewolf)

**Comment by sisimomo** [comment]
No problem! Thanks for your honesty.

@yoinx, @JoshuaMulliken and @brg468, would anyone else be able to fix this?

Otherwise, I will continue to use [simple-wyze-vac](https://github.com/romedtino/simple-wyze-vac). To date, I haven't had any problems. The only chose a bit inheriting is that I have to run a script to update vacuum status. I personally use a slightly modified version of [Noblewolf](https://community.home-assistant.io/u/Noblewolf)'s [blueprint](https://community.home-assistant.io/t/a/358828).

**Comment by brg468** [comment]
> @yoinx, @JoshuaMulliken and @brg468, would anyone else be able to fix this?

Unfortunately I don’t have a Wyze vacuum so I don’t think I’ll be much help here. Like @yoinx said earlier it probably wouldn’t be overly difficult to build, but without being able to get responses and test on an actual vacuum would make this a tall order. Sorry!

**Comment by sisimomo** [comment]
I understand.

But, I can provide you with access to my Wyze account so you can test for yourself. Also, if really needed, I have a Wyze Cam that I could point at the vacuum to give you a visual on the vacuum. In addition, I am a developer myself so I am perfectly able to help you test the new feature.

Otherwise, I'm a Fullstack developer. I could probably be able to do this functionality. Unfortunately I don't have reverse engineering experience. If someone would be willing to give me some of their time to help me I could most certainly add this feature by myself. I already have some basics in Python and have built and used several RESTful APIs in my work.

Anyways, thanks for your time!

**Comment by yoinx** [comment]
The biggest issue is honestly decoding wyze's map. The integration you mentioned before relies on wyzesdk.

You can see the stuff for the vacuum in his code specifically here: https://github.com/shauntarves/wyze-sdk/blob/master/wyze_sdk/service/venus_service.py

Similar functionality would need to be adapted to how wyzeapy does things, like the switch for instance https://github.com/JoshuaMulliken/wyzeapy/blob/main/src/wyzeapy/services/switch_service.py

Obviously everything inherits down in both libraries... So you would need to chase down how the inheritance works. I can say that the biggest obstacle is likely decoding the map file properly from what I saw in your dump.

**Comment by yoinx** [comment]
To follow up on this. The map I think only really matters to serve the vacuum to specific rooms. Simply starting and ending vacuuming and getting the battery level may be significantly easier.

**Comment by JoeSchubert** [comment]
@nameetpai, I'm sure that if you wanted to try to implement this it wouldn't be terribly difficult for simple on/off style commands. As I had said before, the map would be far more difficult to implement, especially through Home Assistant as I think it would require custom cards.

Unfortunately, I don't think anyone else doing any dev work on this project has the robot vac (I recently bought one of the dumb stick vacs, but it does no good here). Without the device, we would all basically be working blind. While it may seem like we could just decode what WyzeSDK is doing or what the app is doing, that is not always as easily done as said.

Where you would need to start with trying to figure out how to implement this would be to intercept the calls between the vacuum/app and Wyze, you can find that info here: https://mulliken.net/p/intercepting-pinned-tls-connections-on-android/

Once you know the API endpoint and the commands, that would need to be implemented in WyzeApy. Then from there, it could be implemented in this codebase to show up in Home Assistant.
