### ISSUE TITLE
[Feature Request] Support 2D barcode recognition for Garage Door Opener

### ISSUE THREAD

**Issue by Vendo232** [SecKatie/ha-wyzeapi#378]
Wyze just introduced a garage opener which registers door open/closed based on specific 2D barcode glued on the garage door.

![image](https://user-images.githubusercontent.com/44098230/165591192-6de80904-fbf6-4d18-9ae6-6b1b3388d9e1.png)

Would something like this be possible to pull in from API -> pushing status to HA?

**Comment by nbetcher** [comment]
I think it's a bit larger scope that simply whether the barcode is present or not... Ideally there would be a controller device and it would respond to Cover HA Services, as well a maintaining the state of the garage door.
@JoshuaMulliken @Vendo232 Does Wyze expose any of this in their API? While I'm a developer and I might be willing to write support, I haven't gotten my feet very wet with Python underpinnings in HA.

I do, however, have a garage door cam + controller fully setup and functional, so I can test any code thrown out there. For safety and automation reasons I'm selling this asap! (Yes, typical user statement, hah!)

Thanks!

**Comment by wesbos** [comment]
Any one able to get this working in home assistant? I expected the sensor to show up in home assistant, but seems only the camera stuff does. I'd love to know if the garage door is open, and to be able to open/close from home assistant

**Comment by nbetcher** [comment]
> Any one able to get this working in home assistant?

Not yet, that I know of. Off-and-on I've been working on, 'politely' trying to drill it into the Wyze app's (Android) skull that I want it to trust all SSL certificates so i can intercept and deciminate the web service payload. I haven't invested much time, but what time I have invested has been met by one after another roadblocks. It's only a matter of time (maybe even today!) until I break this little nut and get its precious little secrets.

I haven't written much Python, let alone implemented a new Home Assistant integration, but since I have 20 years of development behind my ears, it's just (again) a matter of time until I have a PR on PyWyzeAPI's and/or HA-WyzeAPI's front door step. It might take a few weeks or couple of months since I have more projects than time available.

I find it surprising that there's not only no official or draft official Wyze API, but so very little has been reverse engineered of the existing one. You would think that for a company that makes decent products that actually work (and sometimes work well) that Home Assistant integration for Wyze would be booming (this is a diss against Wyze themselves, not this project).

**Comment by nbetcher** [comment]
> Very suprised this isn't working yet either given its popularity.

Well, Wyze goes to painful amounts of effort to protect their API. I spent a few hours yesterday again trying to disable SSL pinning on the Wyze Android APK, only to discover the libc++_shared.so JNI linker error is a clever form of DRM that Wyze has implemented in order to protect the APK from being modified in any way. Even a very minor edit to the Android Manifest XML in the APK triggers the DRM causing the linker error in the resulting APK.

Had I known that this linker error was a DRM mechanism, I would have gone straight to a root solution many days ago. It's fascinating to me that they go to that amount of effort to implement DRM on the APK itself when having root access renders all of that pointless.

They even have additional DRM beyond just the APK decompile — there's another shared library in it that triggers a similar runtime symbol/version resolution failure as a security measure. It gets tripped when you try to use AppCloner on the APK.

I wish these companies would learn once and for all that DRM IS BAD, EVIL, HINDERS ADOPTION OF YOUR PRODUCTS, AND REDUCES SALES, *NOT* the other way around! Fact is, if the Wyze API was open and most/all device types were integrated into Home Assistant OOTB, I would have at least another $600 in Wyze hardware in my apartment.

Instead, I've chosen other products that play well with each other. One of the main reasons for going this way is that Wyze automation in the app is so incredibly over-simplified that it's entirely useless for anything truly productive. (That and it's all hosted in the cloud, so when my internet goes down, which it does all of the time, their automation wouldn't trigger.)

</rant-mode>

I'm still working on it though! Soon!

**Comment by wesbos** [comment]
This isn't a solution, but the reason I wanted this was to get a button on iOS to open the door quickly. This sort of solves that:

https://twitter.com/wesbos/status/1605190126446985217

**Comment by nbetcher** [comment]
> Hey all 👋
> 
> Creator of [bluelinky](https://github.com/Hacksore/bluelinky) which has had its fair share of having to reverse engineer the mobile apps for API endpoints and payloads.
> Hope this helps!

**IT'S CHRISTMAS TIME, SO HERE'S A LITTLE PRESENT...**

Hello. Fortunately, this is all stuff I know already, otherwise it would have taken me months to get to where I may have needed to be.

Even more fortunate is that I've somewhat easily defeated all of Wyze's API security when it comes to what the app receives and transmits. Yes, I have the API dump from the camera / garage door controller. Yes, I'll dissect it over the next few weeks and submit a patch upstream to pyWyzeAPI, and likely to ha-wyzeapi too. Since it's the holidays, maybe it'll take a bit longer, or shorter. :)

NOTE about the garage door controller: I've noticed that this thing is a piece of garbage, if we're being honest. It seemingly crashes every couple of weeks, but you don't really know that it crashed, it just doesn't respond to open/close events. Maybe my hardware is defective, but somehow, I doubt it. If you don't care about being able to open/close your garage door, the camera seems to handle the open/close events fine/indefinitely by using the QR code on the door. As far as I can tell, the garage door controller is only used for two reasons: to make sure you bought the controller, so the camera becomes enabled to read the QR code on your garage door (*laugh*); and to open/close the door (as I said).

PSA to WYZE: Not sure why you spent thousands, possibly millions of dollars on all of this custom and vendor-purchased DRM and security, but maybe that money would be better spent trying to integrate your products instead of stopping us from doing what the pure definition of IoT really is. It's like trying to saw wood against the grain.

**Comment by Hacksore** [comment]
@nbetcher it's funny cause I had a similar workaround before they even made this product with my vehicle detection project 😂😂😂.

https://github.com/Hacksore/garage-plate-detection#wyze-cam-v2

Good to hear you're making progress on this.

Happy holidays!

**Comment by nbetcher** [comment]
> @nbetcher it's funny cause I had a similar workaround before they even made this product with my vehicle detection project 😂😂😂.
> 
> https://github.com/Hacksore/garage-plate-detection#wyze-cam-v2

Frankly, your solution is probably better anyway because it's more secure: it validates YOUR car is in the garage and not someone else's. The only thing missing is the controller box, which is really just a stupid-simple relay with a flashing light and an obnoxious alarm (to comply with local and/or federal laws, I'm sure -- another project I've been meaning to do: disable that crap).

**Comment by alexschwantes** [comment]
@nbetcher, just checking in to see if there has there been any progress? 
If not, are you able to share the API dump, it would save me the time to extract that myself. 

Cheers,

**Comment by nbetcher** [comment]
> @nbetcher, just checking in to see if there has there been any progress? If not, are you able to share the API dump, it would save me the time to extract that myself.

Apologies for not following through with what I said I was going to... I ended up moving and I no longer have a garage for the time being.

I'll look for the API dump files later this morning to see if I still have them. I'm fairly certain I do.
