### ISSUE TITLE
[Feature Request] Switch for Cam Pan V3 Privacy Mode

### ISSUE THREAD

**Issue by spuggy1968** [SecKatie/ha-wyzeapi#604]
Like the Motion Detection On/Off Switch, it would be nice if on a Pan V3 there was a On/Off switch to put the camera in Privacy Mode.   This would allow you to have the camera in plain sight inside your house, but create and automation that when your home it goes to Privacy so people would see the camera is not staring at them :)

**Comment by Abba-** [comment]
@brg468 will be able to confirm, but based on similar discussions with them in the past I doubt this is doable. All of these special camera options (Motion tracking, reset pan, etc) unfortunately dont use the standard wyze api and would likely need to be an entirely different project.

(We can dream of a day where Wyze allows direct local control, or its time for someone to completely emulate the app)

**Comment by Kirby207** [comment]
The switch.<name>.power entity does literally **exactly** what you're asking for...

I have 3 Pan v3's that automatically turn on/off notifications/power (privacy mode) on my phone's GPS leaving/coming home.

The only annoyance I've come across is occasionally the Wyze app still thinks the cameras are in privacy mode when it opens up sometimes, but rarely. They'll be functioning as expected (motion detection/app notifications & recording to SD all working) but the camera view shows it as in privacy mode for some reason. The fix is to hit the privacy mode toggle like you normally would to wake it up, and it'll load the video stream at that point. I'm thinking it's an app desync issue not querying the camera's privacy mode when it opens up and assuming it's last known state is still correct.

**Comment by brg468** [comment]
Thanks @Kirby207, I agree that the power switch is already able to accomplish this. As far as I can tell pushing privacy mode or the power button in the app do the same thing. Closing this as complete.

**Comment by JoshuaSeidel** [comment]
how do you get the power switch on the cameras? just setup mine and there is no power switch. @Kirby207 @brg468

**Comment by encg** [comment]
> how do you get the power switch on the cameras? just setup mine and there is no power switch. [@Kirby207](https://github.com/Kirby207) [@brg468](https://github.com/brg468)

I just set this up via HACS, logged in, and my Pan v3 shows up with power controls: `switch.pan_power`
